### ISSUE TITLE
there is no repo.json for xlplugins installation/update support

### ISSUE THREAD

**Issue by sazo2300** [Onmar/ActAutoEndCombat#1]
Is it possible to get a uri as a 3rd party repo for xlplugins/dalamud support?

**Comment by Onmar** [comment]
So it turns out that this feature is already built into the OverlayPlugin for ACT. (Not the main FFXIV plugin tough)
You can find it via "Plugin" -> "OverlayPlugin.dll" -> "Event Settings" -> "End ACT encounter after wipe"
(You don't need any active overlays for this)

I was not aware of this when I made the Dalamus plugin, but I've since tried it out and it work exactly like I want it to.
It also doesn't clutter the chat log with a bunch of "end" chat messages.

Unless you specifically want the zone filter I would recommend using those options instead.
